# Generated by Django 2.0.7 on 2020-11-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamslide', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberForm',
        ),
    ]
